//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrfKreditScraper.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrfKreditScraper.Tests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;&quot; &quot;&quot;&gt;
        ///&lt;!--[if IE 8]&gt;    &lt;html class=&quot;no-js ie8&quot; lang=&quot;da-DK&quot;&gt; &lt;![endif]--&gt;&lt;!--[if gte IE 9]&gt;&lt;!--&gt;
        ///&lt;HTML class=&quot; js flexbox no-touch cssgradients csstransforms fontface svg boxsizing&quot;
        ///      lang=&quot;da-DK&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;HEAD&gt;
        ///    &lt;META content=&quot;IE=11.0000&quot;
        ///          http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///
        ///    &lt;META charset=&quot;utf-8&quot;&gt;
        ///    &lt;TITLE&gt;
        ///        Realkredit kurser - obligationskurser -
        ///        BRFkredit
        ///    &lt;/TITLE&gt;
        ///    &lt;META name=&quot;description&quot; content=&quot;Se  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kursliste {
            get {
                return ResourceManager.GetString("Kursliste", resourceCulture);
            }
        }
    }
}
