//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koolawong.InterestCalculator.Tests.Services.PeriodPaymentPlanData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PeriodPaymentPlanDataFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodPaymentPlanDataFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koolawong.InterestCalculator.Tests.Services.PeriodPaymentPlanData.PeriodPaymentPl" +
                            "anDataFiles", typeof(PeriodPaymentPlanDataFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 3.500.000,00			
        ///Exchange rate	99			
        ///Yearly interest rate	2,0000%			
        ///Yearly contribution rate	2,0571%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	FALSE			
        ///Bank loan	kr. 300.000,00			
        ///				
        ///Upperstep	Rate			
        ///40,00%	1,50%			
        ///60,00%	2,50%			
        ///80,00%	3,50%			
        ///				
        ///Principal	kr. 3.235.353,54			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,5000%			
        ///Term contribution rate	0,5143%			
        ///Term	Repayment	Interest	Contribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithBankLoan {
            get {
                return ResourceManager.GetString("LoanWithBankLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 2.600.000,00			
        ///Exchange rate	99			
        ///Yearly interest rate	2,0000%			
        ///Yearly contribution rate	1,9615%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	FALSE			
        ///Bank loan	kr. 0,00			
        ///				
        ///Upperstep	Rate			
        ///40,00%	1,50%			
        ///60,00%	2,50%			
        ///80,00%	3,50%			
        ///				
        ///Principal	kr. 2.626.262,63			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,5000%			
        ///Term contribution rate	0,4904%			
        ///Term	Repayment	Interest	Contribution	Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithLessThanUpperLimitPercentagePayout {
            get {
                return ResourceManager.GetString("LoanWithLessThanUpperLimitPercentagePayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 3.200.000,00			
        ///Exchange rate	98,12			
        ///Yearly interest rate	1,5000%			
        ///Yearly contribution rate	0,8000%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	TRUE			
        ///Bank loan	kr. 0			
        ///				
        ///Upperstep	Rate			
        ///40,00%	0,50%			
        ///60,00%	1,00%			
        ///80,00%	1,20%			
        ///				
        ///Principal	kr. 3.261.312,68			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,3750%			
        ///Term contribution rate	0,2000%			
        ///Term	Repayment	Interest	Contribution	Pay [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithOnlyOneProduct {
            get {
                return ResourceManager.GetString("LoanWithOnlyOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 600.000,00			
        ///Exchange rate	98,12			
        ///Yearly interest rate	1,5000%			
        ///Yearly contribution rate	0,8000%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	TRUE			
        ///Bank loan	kr. 0
        ///				
        ///Upperstep	Rate			
        ///40,00%	0,50%			
        ///60,00%	1,00%			
        ///80,00%	1,20%			
        ///				
        ///Principal	kr. 611.496,13			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,3750%			
        ///Term contribution rate	0,2000%			
        ///Term	Repayment	Interest	Contribution	Payment le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithTwoProducts_EntirePayoutDeterminesContributionRate_FirstPriority {
            get {
                return ResourceManager.GetString("LoanWithTwoProducts_EntirePayoutDeterminesContributionRate_FirstPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 2.600.000,00			
        ///Exchange rate	98,12			
        ///Yearly interest rate	1,5000%			
        ///Yearly contribution rate	1,8250%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	TRUE			
        ///Bank loan	kr. 0
        ///				
        ///Upperstep	Rate			
        ///40,00%	1,00%			
        ///60,00%	1,50%			
        ///80,00%	3,80%			
        ///				
        ///Principal	kr. 2.649.816,55			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,3750%			
        ///Term contribution rate	0,4563%			
        ///Term	Repayment	Interest	Contribution	Paymen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithTwoProducts_EntirePayoutDeterminesContributionRate_SecondPriority {
            get {
                return ResourceManager.GetString("LoanWithTwoProducts_EntirePayoutDeterminesContributionRate_SecondPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 600.000,00			
        ///Exchange rate	93,57			
        ///Yearly interest rate	3,5000%			
        ///Yearly contribution rate	0,5000%			
        ///Period	10			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	FALSE			
        ///Bank loan	kr. 0
        ///				
        ///Upperstep	Rate			
        ///40,00%	0,50%			
        ///60,00%	1,00%			
        ///80,00%	1,20%			
        ///				
        ///Principal	kr. 641.231,16			
        ///Terms	40			
        ///Terms per year	4			
        ///Term interest rate	0,8750%			
        ///Term contribution rate	0,1250%			
        ///Term	Repayment	Interest	Contribution	Payment le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithTwoProducts_PriorityDeterminesContributionRate_FirstPriority {
            get {
                return ResourceManager.GetString("LoanWithTwoProducts_PriorityDeterminesContributionRate_FirstPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 2.600.000,00			
        ///Exchange rate	99			
        ///Yearly interest rate	0,5000%			
        ///Yearly contribution rate	2,4231%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	FALSE			
        ///Bank loan	kr. 0
        ///				
        ///Upperstep	Rate			
        ///40,00%	1,50%			
        ///60,00%	2,50%			
        ///80,00%	3,50%			
        ///				
        ///Principal	kr. 2.626.262,63			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,1250%			
        ///Term contribution rate	0,6058%			
        ///Term	Repayment	Interest	Contribution	Payment  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithTwoProducts_PriorityDeterminesContributionRate_SecondPriority {
            get {
                return ResourceManager.GetString("LoanWithTwoProducts_PriorityDeterminesContributionRate_SecondPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout	kr. 3.200.000,00			
        ///Exchange rate	99			
        ///Yearly interest rate	0,0000%			
        ///Yearly contribution rate	2,2500%			
        ///Period	30			
        ///Terms per year	4			
        ///House value	kr. 4.000.000,00			
        ///Entire payout decides contributionrate	FALSE			
        ///Bank loan	kr. 0
        ///				
        ///Upperstep	Rate			
        ///40,00%	1,50%			
        ///60,00%	2,50%			
        ///80,00%	3,50%			
        ///				
        ///Principal	kr. 3.232.323,23			
        ///Terms	120			
        ///Terms per year	4			
        ///Term interest rate	0,0000%			
        ///Term contribution rate	0,5625%			
        ///Term	Repayment	Interest	Contribution	Payment  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoanWithZeroInterestRate {
            get {
                return ResourceManager.GetString("LoanWithZeroInterestRate", resourceCulture);
            }
        }
    }
}
