//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NykreditScraper.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NykreditScraper.Tests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;createTime&quot;: &quot;2016-11-07T00:17:51&quot;,
        ///  &quot;kursliste&quot;: [
        ///    {
        ///      &quot;navn&quot;: &quot;Fastforrentede obligations- og kontantlån&quot;,
        ///      &quot;obligationer&quot;: [
        ///        {
        ///          &quot;isin&quot;: &quot;DK0009504599&quot;,
        ///          &quot;rente&quot;: &quot;0,50&quot;,
        ///          &quot;udloeb&quot;: &quot;2027-10-01T00:00:00&quot;,
        ///          &quot;tilbudskurs&quot;: &quot;98.42&quot;,
        ///          &quot;aktuelkurs&quot;: null,
        ///          &quot;udvikling&quot;: null,
        ///          &quot;renteloft&quot;: null,
        ///          &quot;effektivRente&quot;: null,
        ///          &quot;loebetid&quot;: &quot;10&quot;
        ///        },
        ///        {
        ///          &quot;isin&quot;: &quot;DK000979627 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kursliste {
            get {
                return ResourceManager.GetString("Kursliste", resourceCulture);
            }
        }
    }
}
