//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NordeaScraper.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NordeaScraper.Tests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;rate&quot;: &quot;*&amp;nbsp;102,650&quot;,
        ///    &quot;fundName&quot;: &quot;3,50% NORDEA KREDIT ANNOA10SDRO OA10S&quot;,
        ///    &quot;frequency&quot;: &quot;null&quot;,
        ///    &quot;loanPeriodMax&quot;: &quot;30&quot;,
        ///    &quot;repaymentFreedomMax&quot;: &quot;10&quot;,
        ///    &quot;isinCode&quot;: &quot;203351&quot;
        ///  },
        ///  {
        ///    &quot;rate&quot;: &quot;97,125&quot;,
        ///    &quot;fundName&quot;: &quot;2,00 NORDEA KREDIT REALKREDIT IO 2047&quot;,
        ///    &quot;frequency&quot;: &quot;null&quot;,
        ///    &quot;loanPeriodMax&quot;: &quot;30&quot;,
        ///    &quot;repaymentFreedomMax&quot;: &quot;10&quot;,
        ///    &quot;isinCode&quot;: &quot;203289&quot;
        ///  },
        ///  {
        ///    &quot;rate&quot;: &quot;*&amp;nbsp;102,855&quot;,
        ///    &quot;fundName&quot;: &quot;3,50% NORDEA KREDIT ANN SDRO SDRO 47 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FastRenteKursliste {
            get {
                return ResourceManager.GetString("FastRenteKursliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7 ]&gt;&lt;html class=&quot;ie ie6&quot; lang=&quot;da&quot;&gt; &lt;![endif]--&gt;&lt;!--[if IE 7 ]&gt;&lt;html class=&quot;ie ie7&quot; lang=&quot;da&quot;&gt; &lt;![endif]--&gt;&lt;!--[if IE 8 ]&gt;&lt;html class=&quot;ie ie8&quot; lang=&quot;da&quot;&gt; &lt;![endif]--&gt;&lt;!--[if IE 9 ]&gt;&lt;html class=&quot;ie ie9 &quot;lang=&quot;da&quot;&quot;&gt; &lt;![endif]--&gt;&lt;!--[if (gt IE 9)|!(IE)]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;da&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;link rel=&quot;canonical&quot; href=&quot;http://www.nordea.dk/privat/lan/bolig/historiske-refinansieringsrenter.html&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatibl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlexRenteKursliste {
            get {
                return ResourceManager.GetString("FlexRenteKursliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;refinancingDate&quot;: null,
        ///    &quot;keyFigures&quot;: {
        ///      &quot;principal&quot;: 3031000,
        ///      &quot;disbursementValue&quot;: 101.06,
        ///      &quot;marketValue&quot;: 3057067,
        ///      &quot;proceeds&quot;: 3000850,
        ///      &quot;rateDate&quot;: 1495707300098,
        ///      &quot;contributionFee&quot;: 0.85,
        ///      &quot;interestRate&quot;: 0.16,
        ///      &quot;grossPaymentPerMonth&quot;: 27985,
        ///      &quot;netGrossPaymentPerMonth&quot;: 27317,
        ///      &quot;countyTax&quot;: 27.6,
        ///      &quot;yearlyCostsInPercent&quot;: 1.2,
        ///      &quot;totalGrossPayment&quot;: 3185993.8100000005,
        ///      &quot;totalNetGrossPayment&quot;: 3145678.02234,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KortRenteKursliste20170525OBLC {
            get {
                return ResourceManager.GetString("KortRenteKursliste20170525OBLC", resourceCulture);
            }
        }
    }
}
