//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koolawong.InterestCalculator.Tests.Model.PeriodPaymentPlanData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PeriodPaymentPlanDataFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodPaymentPlanDataFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koolawong.InterestCalculator.Tests.Model.PeriodPaymentPlanData.PeriodPaymentPlanD" +
                            "ataFiles", typeof(PeriodPaymentPlanDataFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	60			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 1.489,30	kr. 375,00	kr. 300,00	kr. 98.510,70
        ///2	kr. 1.494,89	kr. 369,42	kr. 295,53	kr. 97.015,81
        ///3	kr. 1.500,49	kr. 363,81	kr. 291,05	kr. 95.515,32
        ///4	kr. 1.506,12	kr. 358,18	kr. 286,55	kr. 94.009,20
        ///5	kr. 1.511,77	kr. 352,53	kr. 282,03	kr. 92.497,43
        ///6	kr. 1.517,44	kr. 346,87	kr. 277,49	kr. 90.980,00
        ///7	kr. 1.523,13	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FifteenYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("FifteenYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	20			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 4.824,21	kr. 375,00	kr. 300,00	kr. 95.175,79
        ///2	kr. 4.842,30	kr. 356,91	kr. 285,53	kr. 90.333,49
        ///3	kr. 4.860,46	kr. 338,75	kr. 271,00	kr. 85.473,03
        ///4	kr. 4.878,68	kr. 320,52	kr. 256,42	kr. 80.594,35
        ///5	kr. 4.896,98	kr. 302,23	kr. 241,78	kr. 75.697,37
        ///6	kr. 4.915,34	kr. 283,87	kr. 227,09	kr. 70.782,03
        ///7	kr. 4.933,78	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FiveYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("FiveYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	16			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 6.076,08	kr. 375,00	kr. 300,00	kr. 93.923,92
        ///2	kr. 6.098,87	kr. 352,21	kr. 281,77	kr. 87.825,05
        ///3	kr. 6.121,74	kr. 329,34	kr. 263,48	kr. 81.703,31
        ///4	kr. 6.144,70	kr. 306,39	kr. 245,11	kr. 75.558,61
        ///5	kr. 6.167,74	kr. 283,34	kr. 226,68	kr. 69.390,88
        ///6	kr. 6.190,87	kr. 260,22	kr. 208,17	kr. 63.200,01
        ///7	kr. 6.214,08	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("FourYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	4			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 24.859,81	kr. 375,00	kr. 300,00	kr. 75.140,19
        ///2	kr. 24.953,04	kr. 281,78	kr. 225,42	kr. 50.187,15
        ///3	kr. 25.046,61	kr. 188,20	kr. 150,56	kr. 25.140,54
        ///4	kr. 25.140,54	kr. 94,28	kr. 75,42	kr. 0,00
        ///5	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///6	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///7	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///8	kr.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearFourTermsPerYear {
            get {
                return ResourceManager.GetString("OneYearFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	1			
        ///Terms per year	1
        ///Term interest rate	1,50000000%			
        ///Term contribution rate	1,20000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 100.000,00	kr. 1.500,00	kr. 1.200,00	kr. 0,00
        ///2	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///3	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///4	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///5	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///6	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///7	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///8	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///9	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearOneTermPerYear {
            get {
                return ResourceManager.GetString("OneYearOneTermPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	6			
        ///Terms per year	6
        ///Term interest rate	0,25000000%			
        ///Term contribution rate	0,20000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 16.562,80	kr. 250,00	kr. 200,00	kr. 83.437,20
        ///2	kr. 16.604,21	kr. 208,59	kr. 166,87	kr. 66.832,99
        ///3	kr. 16.645,72	kr. 167,08	kr. 133,67	kr. 50.187,27
        ///4	kr. 16.687,34	kr. 125,47	kr. 100,37	kr. 33.499,93
        ///5	kr. 16.729,05	kr. 83,75	kr. 67,00	kr. 16.770,88
        ///6	kr. 16.770,88	kr. 41,93	kr. 33,54	kr. 0,00
        ///7	kr. 0,00	kr. 0,00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearSixTermsPerYear {
            get {
                return ResourceManager.GetString("OneYearSixTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	3			
        ///Terms per year	3
        ///Term interest rate	0,50000000%			
        ///Term contribution rate	0,40000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 33.167,22	kr. 500,00	kr. 400,00	kr. 66.832,78
        ///2	kr. 33.333,06	kr. 334,16	kr. 267,33	kr. 33.499,72
        ///3	kr. 33.499,72	kr. 167,50	kr. 134,00	kr. 0,00
        ///4	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///5	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///6	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///7	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///8	kr. 0,00	kr. 0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearThreeTermsPerYear {
            get {
                return ResourceManager.GetString("OneYearThreeTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	12			
        ///Terms per year	12
        ///Term interest rate	0,12500000%			
        ///Term contribution rate	0,10000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 8.276,20	kr. 125,00	kr. 100,00	kr. 91.723,80
        ///2	kr. 8.286,54	kr. 114,65	kr. 91,72	kr. 83.437,26
        ///3	kr. 8.296,90	kr. 104,30	kr. 83,44	kr. 75.140,36
        ///4	kr. 8.307,27	kr. 93,93	kr. 75,14	kr. 66.833,09
        ///5	kr. 8.317,66	kr. 83,54	kr. 66,83	kr. 58.515,43
        ///6	kr. 8.328,05	kr. 73,14	kr. 58,52	kr. 50.187,38
        ///7	kr. 8.338,46	kr. 62, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearTwelveTermsPerYear {
            get {
                return ResourceManager.GetString("OneYearTwelveTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	2			
        ///Terms per year	2
        ///Term interest rate	0,75000000%			
        ///Term contribution rate	0,60000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 49.813,20	kr. 750,00	kr. 600,00	kr. 50.186,80
        ///2	kr. 50.186,80	kr. 376,40	kr. 301,12	kr. 0,00
        ///3	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///4	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///5	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///6	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///7	kr. 0,00	kr. 0,00	kr. 0,00	kr. 0,00
        ///8	kr. 0,00	kr. 0,00	kr. 0,00	kr. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneYearTwoTermsPerYear {
            get {
                return ResourceManager.GetString("OneYearTwoTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	40			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 2.321,86	kr. 375,00	kr. 300,00	kr. 97.678,14
        ///2	kr. 2.330,57	kr. 366,29	kr. 293,03	kr. 95.347,57
        ///3	kr. 2.339,31	kr. 357,55	kr. 286,04	kr. 93.008,26
        ///4	kr. 2.348,08	kr. 348,78	kr. 279,02	kr. 90.660,18
        ///5	kr. 2.356,89	kr. 339,98	kr. 271,98	kr. 88.303,30
        ///6	kr. 2.365,72	kr. 331,14	kr. 264,91	kr. 85.937,57
        ///7	kr. 2.374,60	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TenYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("TenYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	120			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 661,38	kr. 375,00	kr. 300,00	kr. 99.338,62
        ///2	kr. 663,86	kr. 372,52	kr. 298,02	kr. 98.674,75
        ///3	kr. 666,35	kr. 370,03	kr. 296,02	kr. 98.008,40
        ///4	kr. 668,85	kr. 367,53	kr. 294,03	kr. 97.339,55
        ///5	kr. 671,36	kr. 365,02	kr. 292,02	kr. 96.668,18
        ///6	kr. 673,88	kr. 362,51	kr. 290,00	kr. 95.994,31
        ///7	kr. 676,41	kr. 359,98	kr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirtyYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("ThirtyYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	12			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 8.162,85	kr. 375,00	kr. 300,00	kr. 91.837,15
        ///2	kr. 8.193,46	kr. 344,39	kr. 275,51	kr. 83.643,68
        ///3	kr. 8.224,19	kr. 313,66	kr. 250,93	kr. 75.419,50
        ///4	kr. 8.255,03	kr. 282,82	kr. 226,26	kr. 67.164,47
        ///5	kr. 8.285,99	kr. 251,87	kr. 201,49	kr. 58.878,48
        ///6	kr. 8.317,06	kr. 220,79	kr. 176,64	kr. 50.561,42
        ///7	kr. 8.348,25	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThreeYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("ThreeYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	80			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 1.074,19	kr. 375,00	kr. 300,00	kr. 98.925,81
        ///2	kr. 1.078,21	kr. 370,97	kr. 296,78	kr. 97.847,60
        ///3	kr. 1.082,26	kr. 366,93	kr. 293,54	kr. 96.765,34
        ///4	kr. 1.086,32	kr. 362,87	kr. 290,30	kr. 95.679,03
        ///5	kr. 1.090,39	kr. 358,80	kr. 287,04	kr. 94.588,64
        ///6	kr. 1.094,48	kr. 354,71	kr. 283,77	kr. 93.494,16
        ///7	kr. 1.098,58	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwentyYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("TwentyYearsFourTermsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal	kr. 100.000,00			
        ///Terms	8			
        ///Terms per year	4
        ///Term interest rate	0,37500000%			
        ///Term contribution rate	0,30000000%			
        ///Term	Repayment	Interest	Contribution	Payment left
        ///1	kr. 12.336,86	kr. 375,00	kr. 300,00	kr. 87.663,14
        ///2	kr. 12.383,12	kr. 328,74	kr. 262,99	kr. 75.280,02
        ///3	kr. 12.429,56	kr. 282,30	kr. 225,84	kr. 62.850,46
        ///4	kr. 12.476,17	kr. 235,69	kr. 188,55	kr. 50.374,29
        ///5	kr. 12.522,96	kr. 188,90	kr. 151,12	kr. 37.851,34
        ///6	kr. 12.569,92	kr. 141,94	kr. 113,55	kr. 25.281,42
        ///7	kr. 12.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoYearsFourTermsPerYear {
            get {
                return ResourceManager.GetString("TwoYearsFourTermsPerYear", resourceCulture);
            }
        }
    }
}
